import type { Movie } from './types';

export const placeholderMovies: Movie[] = [
  // Action
  { id: 'p-action-1', title: 'Cyber Strike', description: 'In a dystopian future, a lone warrior fights to free humanity from an oppressive AI.', genre: 'Action', videoURL: '', thumbnailURL: 'https://picsum.photos/seed/a1/500/281', backdropURL: 'https://picsum.photos/seed/ba1/1280/720', releaseYear: '2024', isPremium: false },
  { id: 'p-action-2', title: 'Jungle Fury', description: 'An elite squad is sent on a perilous mission deep in the Amazon rainforest.', genre: 'Action', videoURL: '', thumbnailURL: 'https://picsum.photos/seed/a2/500/281', backdropURL: 'https://picsum.photos/seed/ba2/1280/720', releaseYear: '2023', isPremium: true },
  { id: 'p-action-3', title: 'Speed Demon', description: 'A getaway driver is pulled back in for one last job.', genre: 'Action', videoURL: '', thumbnailURL: 'https://picsum.photos/seed/a3/500/281', backdropURL: 'https://picsum.photos/seed/ba3/1280/720', releaseYear: '2024', isPremium: false },
  { id: 'p-action-4', title: 'Zero Hour', description: 'A team of specialists must defuse a series of bombs planted across the city.', genre: 'Action', videoURL: '', thumbnailURL: 'https://picsum.photos/seed/a4/500/281', backdropURL: 'https://picsum.photos/seed/ba4/1280/720', releaseYear: '2022', isPremium: false },
  { id: 'p-action-5', title: 'Maritime Siege', description: 'Pirates take over a massive cargo ship, and only one crew member can stop them.', genre: 'Action', videoURL: '', thumbnailURL: 'https://picsum.photos/seed/a5/500/281', backdropURL: 'https://picsum.photos/seed/ba5/1280/720', releaseYear: '2023', isPremium: false },

  // Comedy
  { id: 'p-comedy-1', title: 'Mishap Island', description: 'A group of tourists gets stranded on a deserted island with a clumsy guide.', genre: 'Comedy', videoURL: '', thumbnailURL: 'https://picsum.photos/seed/c1/500/281', backdropURL: 'https://picsum.photos/seed/bc1/1280/720', releaseYear: '2023', isPremium: false },
  { id: 'p-comedy-2', title: 'The Wrong Switch', description: 'Two identical briefcases are accidentally switched, with hilarious consequences.', genre: 'Comedy', videoURL: '', thumbnailURL: 'https://picsum.photos/seed/c2/500/281', backdropURL: 'https://picsum.photos/seed/bc2/1280/720', releaseYear: '2024', isPremium: false },
  { id: 'p-comedy-3', title: 'Cubicle Chaos', description: 'An office drone decides to live out his fantasies during a boring workday.', genre: 'Comedy', videoURL: '', thumbnailURL: 'https://picsum.photos/seed/c3/500/281', backdropURL: 'https://picsum.photos/seed/bc3/1280/720', releaseYear: '2022', isPremium: true },
  { id: 'p-comedy-4', title: 'My Alien Roommate', description: 'A struggling artist\'s life is turned upside down when an alien crash-lands in his apartment.', genre: 'Comedy', videoURL: '', thumbnailURL: 'https://picsum.photos/seed/c4/500/281', backdropURL: 'https://picsum.photos/seed/bc4/1280/720', releaseYear: '2024', isPremium: false },
  { id: 'p-comedy-5', title: 'Grandma\'s Secret', description: 'Two siblings discover their sweet old grandma was a spy in her youth.', genre: 'Comedy', videoURL: '', thumbnailURL: 'https://picsum.photos/seed/c5/500/281', backdropURL: 'https://picsum.photos/seed/bc5/1280/720', releaseYear: '2023', isPremium: false },
  
  // Science Fiction
  { id: 'p-scifi-1', title: 'Galaxy\'s Edge', description: 'A renegade crew on a smuggling ship stumbles upon a secret that could change the galaxy.', genre: 'Science Fiction', videoURL: '', thumbnailURL: 'https://picsum.photos/seed/sf1/500/281', backdropURL: 'https://picsum.photos/seed/bsf1/1280/720', releaseYear: '2024', isPremium: true },
  { id: 'p-scifi-2', title: 'Chrono-Shift', description: 'A scientist invents a device that allows him to jump through time, but at a great cost.', genre: 'Science Fiction', videoURL: '', thumbnailURL: 'https://picsum.photos/seed/sf2/500/281', backdropURL: 'https://picsum.photos/seed/bsf2/1280/720', releaseYear: '2023', isPremium: false },
  { id: 'p-scifi-3', title: 'The Last Terran', description: 'After Earth\'s evacuation, one human is left behind on a planet now inhabited by aliens.', genre: 'Science Fiction', videoURL: '', thumbnailURL: 'https://picsum.photos/seed/sf3/500/281', backdropURL: 'https://picsum.photos/seed/bsf3/1280/720', releaseYear: '2024', isPremium: false },
  { id: 'p-scifi-4', title: 'Mind Weaver', description: 'In a world where thoughts can be read, a rebel group fights for mental privacy.', genre: 'Science Fiction', videoURL: '', thumbnailURL: 'https://picsum.photos/seed/sf4/500/281', backdropURL: 'https://picsum.photos/seed/bsf4/1280/720', releaseYear: '2022', isPremium: false },
  { id: 'p-scifi-5', title: 'Orbital Decay', description: 'The crew of a space station must fight for survival as their orbit begins to decay.', genre: 'Science Fiction', videoURL: '', thumbnailURL: 'https://picsum.photos/seed/sf5/500/281', backdropURL: 'https://picsum.photos/seed/bsf5/1280/720', releaseYear: '2023', isPremium: false },

  // Drama
  { id: 'p-drama-1', title: 'The Long Road Home', description: 'A soldier struggles to readjust to civilian life after returning from war.', genre: 'Drama', videoURL: '', thumbnailURL: 'https://picsum.photos/seed/d1/500/281', backdropURL: 'https://picsum.photos/seed/bd1/1280/720', releaseYear: '2023', isPremium: false },
  { id: 'p-drama-2', title: 'Faded Photograph', description: 'A young woman uncovers a family secret while going through her late grandmother\'s belongings.', genre: 'Drama', videoURL: '', thumbnailURL: 'https://picsum.photos/seed/d2/500/281', backdropURL: 'https://picsum.photos/seed/bd2/1280/720', releaseYear: '2024', isPremium: false },
  { id: 'p-drama-3', title: 'The Artist\'s Muse', description: 'A painter\'s life is forever changed by the mysterious woman who becomes his inspiration.', genre: 'Drama', videoURL: '', thumbnailURL: 'https://picsum.photos/seed/d3/500/281', backdropURL: 'https://picsum.photos/seed/bd3/1280/720', releaseYear: '2022', isPremium: false },
  { id: 'p-drama-4', title: 'City of Echoes', description: 'An old detective is haunted by an unsolved case from his past.', genre: 'Drama', videoURL: '', thumbnailURL: 'https://picsum.photos/seed/d4/500/281', backdropURL: 'https://picsum.photos/seed/bd4/1280/720', releaseYear: '2023', isPremium: true },
  { id: 'p-drama-5', title: 'Winds of Change', description: 'A farming family struggles to hold on to their land during a time of great economic upheaval.', genre: 'Drama', videoURL: '', thumbnailURL: 'https://picsum.photos/seed/d5/500/281', backdropURL: 'https://picsum.photos/seed/bd5/1280/720', releaseYear: '2024', isPremium: false },

  // Horror
  { id: 'p-horror-1', title: 'The Whispering House', description: 'A family moves into a new home, only to discover it has a dark and terrifying past.', genre: 'Horror', videoURL: '', thumbnailURL: 'https://picsum.photos/seed/h1/500/281', backdropURL: 'https://picsum.photos/seed/bh1/1280/720', releaseYear: '2023', isPremium: true },
  { id: 'p-horror-2', title: 'Beneath the Lake', description: 'A group of friends on a camping trip awakens an ancient evil lurking in the depths of the lake.', genre: 'Horror', videoURL: '', thumbnailURL: 'https://picsum.photos/seed/h2/500/281', backdropURL: 'https://picsum.photos/seed/bh2/1280/720', releaseYear: '2024', isPremium: false },
  { id: 'p-horror-3', title: 'Don\'t Turn Around', description: 'A college student is stalked by a relentless, unseen entity.', genre: 'Horror', videoURL: '', thumbnailURL: 'https://picsum.photos/seed/h3/500/281', backdropURL: 'https://picsum.photos/seed/bh3/1280/720', releaseYear: '2022', isPremium: false },
  { id: 'p-horror-4', title: 'The Midnight Broadcast', description: 'A pirate radio host receives a disturbing call that leads him into a world of darkness.', genre: 'Horror', videoURL: '', thumbnailURL: 'https://picsum.photos/seed/h4/500/281', backdropURL: 'https://picsum.photos/seed/bh4/1280/720', releaseYear: '2023', isPremium: false },
  { id: 'p-horror-5', title: 'Harvest of Fear', description: 'A remote farming community\'s annual festival takes a sinister turn.', genre: 'Horror', videoURL: '', thumbnailURL: 'https://picsum.photos/seed/h5/500/281', backdropURL: 'https://picsum.photos/seed/bh5/1280/720', releaseYear: '2024', isPremium: false },
];
